-- insert into users values (0,'gaston','GFDA23faS$#','gdeschant@itba.edu.ar','the best teacher ever','every day since 8 am to 4 pm')
-- ,(1,'brittany','FDSAVA234#','blin@itba.edu.ar','the second best teacher ever','every day since 12 am to 3 pm');
-- insert into rating values (0,1,4.5,'the teacher on my life'),(1,0,1.5,'not bad but ...');
-- insert into favourites values (0,1);
-- insert into subject values ( 0,'matematica' ),(1,'ingles');
-- insert into roles values (0,'USER_TEACHER'),(1,'USER_STUDENT');
-- insert into teaches values ( 0, 0,1200,1),(0,1,1500,2);
-- -- insert into classes values (0,1,1,0,1200,0,);